/**
 * Stable, machine-readable error codes (§14.1).
 *
 * `message` may change; `code` is the contract the frontends switch on.
 * A unit test asserts every value here is unique.
 */
export const ERROR_CODES = {
  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',

  // Authentication
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  // Deliberately one code for unknown email, wrong password, disabled and
  // locked accounts. Distinguishing them would be an enumeration oracle (§6.4).
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  /** Returned on an authenticated request once the account is turned off. */
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  WEAK_PASSWORD: 'WEAK_PASSWORD',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROLE_ASSIGNMENT_FORBIDDEN: 'ROLE_ASSIGNMENT_FORBIDDEN',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',

  // Not found
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

  // Conflict
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  RESOURCE_BUSY: 'RESOURCE_BUSY',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',

  // Gone
  LINK_EXPIRED: 'LINK_EXPIRED',

  // Domain rules
  REFERENCED_RESOURCE_MISSING: 'REFERENCED_RESOURCE_MISSING',
  DOMAIN_RULE_VIOLATION: 'DOMAIN_RULE_VIOLATION',

  // Catalogue
  HANDLE_TAKEN: 'HANDLE_TAKEN',
  SKU_TAKEN: 'SKU_TAKEN',
  VARIANT_COMBINATION_EXISTS: 'VARIANT_COMBINATION_EXISTS',
  INVALID_OPTION_SELECTION: 'INVALID_OPTION_SELECTION',
  OPTION_VALUE_IN_USE: 'OPTION_VALUE_IN_USE',
  PRODUCT_NOT_PUBLISHABLE: 'PRODUCT_NOT_PUBLISHABLE',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  LAST_VARIANT_PROTECTED: 'LAST_VARIANT_PROTECTED',
  CATEGORY_CYCLE: 'CATEGORY_CYCLE',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',

  // Inventory
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_NOT_TRACKED: 'INVENTORY_NOT_TRACKED',
  RESERVATION_EXISTS: 'RESERVATION_EXISTS',
  RESERVATION_ALREADY_RESOLVED: 'RESERVATION_ALREADY_RESOLVED',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  LOCATION_IN_USE: 'LOCATION_IN_USE',
  LAST_LOCATION_PROTECTED: 'LAST_LOCATION_PROTECTED',

  // Orders, payments, shipping, discounts
  INVALID_ORDER_TRANSITION: 'INVALID_ORDER_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  CART_EMPTY: 'CART_EMPTY',
  CART_NOT_PURCHASABLE: 'CART_NOT_PURCHASABLE',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  REFUND_EXCEEDS_PAYMENT: 'REFUND_EXCEEDS_PAYMENT',
  NO_SHIPPING_METHOD: 'NO_SHIPPING_METHOD',
  SHIPPING_UNAVAILABLE: 'SHIPPING_UNAVAILABLE',
  DISCOUNT_INVALID: 'DISCOUNT_INVALID',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_USAGE_EXCEEDED: 'DISCOUNT_USAGE_EXCEEDED',
  DISCOUNT_MINIMUM_NOT_MET: 'DISCOUNT_MINIMUM_NOT_MET',
  PAYMENT_METHOD_INVALID: 'PAYMENT_METHOD_INVALID',
  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',
  DISCOUNT_REQUIRES_ACCOUNT: 'DISCOUNT_REQUIRES_ACCOUNT',

  // Media
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_NOT_UPLOADED: 'MEDIA_NOT_UPLOADED',
  MEDIA_REJECTED: 'MEDIA_REJECTED',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // External / internal
  EMAIL_PROVIDER_ERROR: 'EMAIL_PROVIDER_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
