/**
 * Request identity and ambient context (§15.1).
 *
 * The request id is generated by the server, never taken from the client — a
 * client-supplied id would let a caller poison log correlation. A client's own
 * correlation header is preserved as a separate field.
 */
import type { NextFunction, Request, Response } from 'express'
import { v7 as uuidv7 } from 'uuid'
import { REQUEST_ID_HEADER } from '../../config/index.js'
import { runWithContext } from '../../infrastructure/logging/context.js'

declare module 'express-serve-static-core' {
  interface Request {
    requestId: string
  }
}

export function requestContext(req: Request, res: Response, next: NextFunction): void {
  const requestId = uuidv7()
  req.requestId = requestId
  res.setHeader(REQUEST_ID_HEADER, requestId)

  runWithContext({ requestId }, () => next())
}
