-- 0006_settings_and_media.sql
-- Store settings, media assets, and the staff-invitation token purpose (§5.3).
-- Forward-only. Never edit a migration that has been applied (§4.4).

-- ─────────────────────────────────────────────────────────────────────────────
-- store_settings — business configuration the owner changes in the admin UI.
--
-- Distinct from environment variables (§21.2): store name, currency, timezone
-- and tax rate must be changeable without a deploy. One row, enforced by the
-- primary key check, so "the settings" is never ambiguous.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE store_settings (
  id                          smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  store_name                  text NOT NULL,
  contact_email               citext NOT NULL,
  support_url                 text,
  support_phone               text,
  currency                    char(3) NOT NULL DEFAULT 'USD'
                                CHECK (currency ~ '^[A-Z]{3}$'),
  timezone                    text NOT NULL DEFAULT 'UTC',
  weight_unit                 text NOT NULL DEFAULT 'g'
                                CHECK (weight_unit IN ('g', 'kg', 'lb', 'oz')),
  -- Basis points, so tax is integer arithmetic end to end (§4.1 rule 2).
  tax_rate_bps                integer NOT NULL DEFAULT 0
                                CHECK (tax_rate_bps BETWEEN 0 AND 10000),
  prices_include_tax          boolean NOT NULL DEFAULT false,
  default_low_stock_threshold integer NOT NULL DEFAULT 5
                                CHECK (default_low_stock_threshold >= 0),
  order_number_prefix         text NOT NULL DEFAULT '#',
  reservation_ttl_minutes     integer NOT NULL DEFAULT 60
                                CHECK (reservation_ttl_minutes > 0),
  guest_checkout_enabled      boolean NOT NULL DEFAULT true,
  logo_media_id               uuid,
  metadata                    jsonb NOT NULL DEFAULT '{}',
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),
  updated_by                  uuid REFERENCES users(id) ON DELETE SET NULL
);

CREATE TRIGGER store_settings_set_updated_at
  BEFORE UPDATE ON store_settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- The row is seeded here rather than by a script: every environment must have
-- settings from the first request, and a missing row would be a null check in
-- every caller forever.
INSERT INTO store_settings (id, store_name, contact_email)
VALUES (1, 'My Store', 'store@example.com');

COMMENT ON TABLE store_settings IS
  'Single-row store configuration. Changeable by the owner without a deploy.';

-- ─────────────────────────────────────────────────────────────────────────────
-- media_assets — one row per uploaded object, with an explicit lifecycle.
--
--   pending    → a signed upload URL was issued; no bytes verified yet
--   processing → bytes arrived and passed inspection; the worker has it
--   ready      → re-encoded, variants generated, safe to serve
--   failed     → inspection or processing rejected it
--
-- The status exists because an upload goes straight to object storage: until
-- the server has inspected the object it is untrusted input, and nothing may
-- reference it (§16.3).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE media_assets (
  id                uuid PRIMARY KEY,
  -- Generated by the server, never supplied by a client (§16.3).
  storage_key       text NOT NULL UNIQUE,
  bucket            text NOT NULL,
  status            text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
  -- What the client declared at request time. Verified against the real bytes
  -- before the asset ever reaches 'ready'.
  declared_mime     text NOT NULL,
  mime_type         text,
  byte_size         integer CHECK (byte_size IS NULL OR byte_size >= 0),
  width             integer CHECK (width IS NULL OR width > 0),
  height            integer CHECK (height IS NULL OR height > 0),
  checksum_sha256   text,
  original_filename text,
  alt               text,
  -- { "thumb": {"key":"…","width":200,"height":200}, … }
  variants          jsonb NOT NULL DEFAULT '{}',
  failure_reason    text,
  uploaded_by       uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ready_assets_are_described CHECK (
    status <> 'ready' OR (mime_type IS NOT NULL AND byte_size IS NOT NULL)
  ),
  CONSTRAINT failed_assets_say_why CHECK (
    status <> 'failed' OR failure_reason IS NOT NULL
  )
);

CREATE TRIGGER media_assets_set_updated_at
  BEFORE UPDATE ON media_assets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX media_assets_status_idx ON media_assets (status, created_at DESC);
CREATE INDEX media_assets_created_idx ON media_assets (created_at DESC);
-- Drives the abandoned-upload sweep: stays tiny because most rows leave 'pending'.
CREATE INDEX media_assets_pending_idx ON media_assets (created_at) WHERE status = 'pending';

COMMENT ON TABLE media_assets IS
  'Uploaded objects. Untrusted until inspected and re-encoded; only "ready" may be served.';
COMMENT ON COLUMN media_assets.storage_key IS
  'Server-generated object key. A client never chooses a bucket, path or filename.';

ALTER TABLE store_settings
  ADD CONSTRAINT store_settings_logo_media_fk
  FOREIGN KEY (logo_media_id) REFERENCES media_assets(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- Staff invitations reuse the credential-token machinery with their own purpose
-- and a longer lifetime: an invitation is expected to sit in an inbox for days,
-- whereas a password reset should not.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE auth_tokens DROP CONSTRAINT auth_tokens_purpose_check;
ALTER TABLE auth_tokens ADD CONSTRAINT auth_tokens_purpose_check
  CHECK (purpose IN ('email_verify', 'password_reset', 'staff_invite'));
